# Dockerfile para o backend
FROM openjdk:17-jdk-slim AS builder

WORKDIR /build

COPY ./backend ./backend

RUN ./mvnw package -DskipTests

RUN mv target/*.jar app.jar

FROM openjdk:17-jre-slim

ENV TZ=America/Fortaleza

RUN addgroup -S spring && adduser -S spring -G spring
USER spring:spring

VOLUME /tmp

WORKDIR /backend/app

COPY --from=builder /build/app.jar /backend/app/app.jar

CMD ["java", "-jar", "app.jar"]

