version: '3.8'
services:
  backend:
    build: ./backend/
    ports:
      - "8085:8080"
    volumes:
      - ./backend:/backend
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      
  database:
      image: postgres:latest
      restart: always
      environment:
        POSTGRES_USER: ${DB_USERNAME}
        POSTGRES_PASSWORD: ${DB_PASSWORD}
        POSTGRES_DB: ${DB_DATABASE}
      ports:
        - "5433:5432"

volumes: 
  nodemodules: {}