version: '3.8'
services:
  backend:
    build: ./backend/
    ports:
      - "8085:8080"
    volumes:
      - ./backend:/backend
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}

  frontend: 
      container_name: frontend
      build: ./frontend/
      ports:
         - 19000:19000 
         - 19001:19001
         - 19002:19002
      volumes:
         - ./frontend/:/usr/app # Link host directory to container
         - nodemodules:/usr/app/node_modules
      env_file: .env

  database:
      image: postgres:latest
      restart: always
      environment:
        POSTGRES_USER: ${DB_USERNAME}
        POSTGRES_PASSWORD: ${DB_PASSWORD}
        POSTGRES_DB: ${DB_DATABASE}
      ports:
        - "5433:5432"

volumes: 
  nodemodules: {}