name: DEV - Build & Deploy

on:
  push:
    branches: ["develop"]
  pull_request:
    branches: ["develop"]

jobs:
  lint:
    name: Lint Codebase
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.x

      - name: Install dependencies
        run: npm install
        working-directory: frontend

      - name: Run lint
        run: npm run lint
        working-directory: frontend

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.x

      - name: Install dependencies
        run: npm install
        working-directory: frontend

      - name: Run tests
        run: npm test
        working-directory: frontend

  build:
    name: Build Android
    runs-on: ubuntu-latest
    needs: test
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        run: npm install
        working-directory: frontend

      - name: Install EAS CLI
        run: npm install -g eas-cli
        working-directory: frontend

      - name: Set EXPO_TOKEN environment variable
        run: echo "EXPO_TOKEN=${{ secrets.EXPO_TOKEN }}" >> $GITHUB_ENV

      - name: Run build for Android
        run: npm run build:android
        working-directory: frontend

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: frontend/build/android/*.apk  # Ajuste o caminho conforme necessário

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'

    steps:
      - name: Download APK artifact
        uses: actions/download-artifact@v4
        with:
          name: android-apk
          path: frontend/build/android

      - name: Deploy to a distribution service
        run: echo "Deploy step here"  # Adicione o comando de deploy adequado
